### ISSUE TITLE
(epic): Establish calling convention

### ISSUE THREAD

**Issue by arkamnite** [arkamnite/llvm-project#14]
> Establish a calling convention for the Game Boy.

This is a major task which is required in order to complete most other tasks. The existing AVR calling convention must be studied and understood completely to see where it can be adapted to suit the Game Boy best. The tasks are therefore as follows:

- [x] Study AVR calling convention
- [x] Study SDCC Z80 calling convention
- [x] Determine existing overlap
- [x] If there are major discrepancies between the two, then decide which one should be maintained / which features should be maintained from either.
- [x] Document and formalise this.

**Comment by arkamnite** [comment]
See Notion page for further details; SDCC V0 and SDCC V1 have been identified as valid contenders for calling conventions.
