### ISSUE TITLE
(epic): Establish better calling convention

### ISSUE THREAD

**Issue by arkamnite** [arkamnite/llvm-project#17]
# (epic): Establish better calling convention

After consulting with the gbdev community, it is apparent that there is a desire for a new calling convention. Research needs to take place to better understand the implications of using different components of memory on the Game Boy system.

- [x] Research Game Boy hardware more thoroughly (full insight needed for memory).
- [x] Research how stack usage can be mitigated.
- [x] Map options ranging from full stack usage to minimal stack usage (global variables).
- [x] Add any new calling conventions into `CallingConv.h`.

**Comment by arkamnite** [comment]
Currently, only one calling convention will be used. This is referred to in the relevant research paper which is what was eventually implemented in SDCC's ABI. No further calling conventions will be needed for the time being.
